name 'evenup-backups'
version '0.10.5'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'http://www.letsevenup.com'
summary 'Manages backups'
description 'Installs and configures backup scripts, config files, and cron entries'
dependency 'evenup/ruby', '>= 1.3.4'
dependency 'ripienaar/concat', '>= 0.2.0'

