name 'evenup-backups'
version '1.1.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'http://www.letsevenup.com'
summary 'Manages backups'
description 'Installs and configures backup scripts, config files, and cron entries'
dependency 'ripienaar/concat', '>= 0.2.0'
